name: Build Tweak

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        brew install ldid
        git clone --recursive https://github.com/theos/theos.git ~/theos
        export THEOS=~/theos
    
    - name: Build Tweak
      run: |
        export THEOS=~/theos
        cd ${{ github.workspace }}
        make clean
        make
    
    - name: Upload DEB artifact
      uses: actions/upload-artifact@v3
      with:
        name: OneStateMoumenMod-DEB
        path: packages/*.deb
        
    - name: Upload Dylib artifact
      uses: actions/upload-artifact@v3
      with:
        name: OneStateMoumenMod-DYLIB
        path: .theos/obj/debug/
